# Generated by Django 4.0 on 2021-12-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_manager', '0002_remove_ad_clicks_remove_ad_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
