# Generated by Django 4.0 on 2022-01-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_manager', '0003_ad_approve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='ad_id',
            new_name='ad',
        ),
        migrations.AddField(
            model_name='click',
            name='view',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advertiser_manager.view'),
        ),
    ]
