# Generated by Django 4.0 on 2022-01-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_manager', '0004_rename_ad_id_click_ad_click_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='view',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='advertiser_manager.view'),
        ),
    ]
