# Generated by Django 4.0 on 2022-01-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_manager', '0005_alter_click_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='ad',
            new_name='ad_id',
        ),
    ]
