# Generated by Django 4.0 on 2022-01-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_manager', '0006_rename_ad_click_ad_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='click',
            old_name='ad_id',
            new_name='ad',
        ),
        migrations.AlterField(
            model_name='click',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser_manager.view'),
        ),
    ]
