# Generated by Django 4.0 on 2022-01-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_manager', '0007_rename_ad_id_click_ad_alter_click_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='ad_id',
            new_name='ad',
        ),
    ]
