# Generated by Django 4.0 on 2022-01-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_manager', '0008_rename_ad_id_view_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='ad',
        ),
    ]
